### ISSUE TITLE
Method delete is causing AxiosError

### ISSUE THREAD

**Issue by l-maciej** [fjogeleit/http-request-action#106]
I've noticed that using action with delete method throws 501 error without any message

`{"name":"AxiosError","message":"Request failed with status code 501","code":"ERR_BAD_RESPONSE","status":501}`

Action that was ran in GH: 

```        
name: drop-vm
        id: drop-vm
        uses: fjogeleit/http-request-action@v1
        with: 
          url: ${{secrets.PVE_ENDPOINT}}/nodes/somenode/qemu/${{steps.get-id.outputs.ID}}/?purge=1
          method: 'DELETE'
          customHeaders: '{"Authorization": "PVEAPIToken=${{secrets.PVE_TOKEN}}"}'
          httpsCA: ${{secrets.HL_CA}}
```

Rendered URL seems to be valid (xxxxx/nodes/somenode/qemu/108/?purge=1).
![image](https://github.com/fjogeleit/http-request-action/assets/95386532/68777b1b-6c5b-4995-b02a-31de051d7df0)

When pasted to Postman and used with same credentials action is successful.
