### ISSUE TITLE
Array of files to upload in single files property fails

### ISSUE THREAD

**Issue by mrcnk** [fjogeleit/http-request-action#120]
Hi, thanks for this action, helps a lot.

I'd like the `multipart/form-data` files upload to work like:
```
files: '{"attachments": ["report.html", "report.json"]}'
```
This is what a CMS I use for one of my apps accepts.
Using it with the action produces:
```
{"message":"Unable to convert Data and Files into FormData: The \"path\" argument must be of type string or an instance of Buffer or URL. Received an instance of Array","data":{"jobId":"u4oigjysc5lzwkg"},"files":{"attachments":["report.html","report.json"]}}
```

**Comment by fjogeleit** [comment]
hey, I'll have a look. What would be the expected key?

```json
{
 "files[0]": report.html file,
 "files[1]": report.html file
}
```

something like this?

**Comment by fjogeleit** [comment]
Could you please if its working with `fjogeleit/http-request-action@support-file-array`?

I added a basic test action, so it looks good but would like your confirmation before I release it.

**Comment by mrcnk** [comment]
Sure, so my step looks like this:
```
- name: Upload Report
    uses: fjogeleit/http-request-action@support-file-array
    with:
      url: https://seonow.sh.palladians.xyz/api/collections/reports/records
      method: POST
      contentType: multipart/form-data
      bearerToken: ${{ secrets.API_ADMIN_SECRET_KEY }}
      customHeaders: '{"Content-Type": "application/json"}'
      data: '{"jobId": "${{ github.event.inputs.jobId }}"}'
      files: '{"attachments": [".lighthouseci/report.html", ".lighthouseci/report.json"]}'
```
And when executed, I get a mimetype error:
```
{"code":400,"message":{"code":400,"message":"Something went wrong while processing your request.","data":{"attachments":{"code":"validation_invalid_mime_type","message":"\"report_vETdVgmY8E.html\" mime type must be one of: text/html, application/pdf, image/png, image/jpeg, application/json."}}}}
```
However, as you can see in the error message, `text/html` is allowed.
