### ISSUE TITLE
Pass data through json file 

### ISSUE THREAD

**Issue by Nayana-Nagaraj** [fjogeleit/http-request-action#129]
Hello,

As we are making REST API call, instead of passing data directly we would like to input the path to json file which consits data.
Can you please help us to acheive the same.

Thanks & Regards,
Nayana Nagaraj

**Comment by fjogeleit** [comment]
Hey, I think this should be doable by putting the file content into a variable and then pass the data via the variable

```yaml
- name: Get Data
  run: |
    echo "DATA=$(cat ./content.json)" >> $GITHUB_ENV

- name: Example
   uses: fjogeleit/http-request-action@v1
     with:
       url: 'https://exmaple.de'
       method: 'POST'
       data: ${{ DATA }}
```
