### ISSUE TITLE
Update v1 tag to latest (1.15.2)

### ISSUE THREAD

**Issue by randyshoopman** [fjogeleit/http-request-action#133]
Please tag 1.15.2 as v1.   It brings in Node 20 which GitHub Actions is complaining about:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: fjogeleit/http-request-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Thanks

**Comment by fjogeleit** [comment]
done

**Comment by mahesh-gritfi** [comment]
Am facing the same issue, so what would be the resolution for this? is it just changing action  from `uses: fjogeleit/http-request-action@v1`  to `uses: fjogeleit/http-request-action@v1.15.2`? or is there something more to it?

**Comment by fjogeleit** [comment]
`fjogeleit/http-request-action@v1` points to the same commit as `fjogeleit/http-request-action@v1.5.2`, so it should not make any difference, both tags using node v20 (https://github.com/fjogeleit/http-request-action/blob/v1/action.yml#L78)

Maybe you have some caching which was not updated? You could try to use a pinned version like `fjogeleit/http-request-action@v1.15.2` but `v1` should also work.

**Comment by mahesh-gritfi** [comment]
I tried using `fjogeleit/http-request-action@v1.15.2` still getting the following error:

>`Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load fjogeleit/http-request-action/v1.15.2/action.yml`
I even cleared the workflow cache for that repo. Could it be a server issue?

**Comment by fjogeleit** [comment]
Thats a totally different issue, looks like your runner does not support node20. Maybe you use outdated machines?

**Comment by mahesh-gritfi** [comment]
I am using ubuntu 20.04 EC2 instance on AWS, the instance doesn't seems to be the issue here.

**Comment by fjogeleit** [comment]
As your issue describes:

Your runner does not support Node20, only lower versions like Node16 but this versions are deprecated for GitHub Runners.

You can either use an older version of this action before v1.15.2, or you need to update your Runner instances to support Node v20.

**Comment by mahesh-gritfi** [comment]
This is my workflow file
```

name: Delete User

on:
  workflow_dispatch:
    inputs:
      phoneNumber:
        description: 'User phone number with country code'
        required: true
        default: '+1'
      environment:
        description: 'The environment. Eg: sandbox, uat'
        required: true
        default: 'sandbox'

jobs:
  delete_user:
    runs-on: ${{ github.event.inputs.environment }}
    steps:
      - name: Delete User
        id: deleteUser
        uses: fjogeleit/http-request-action@v1.15.2
        with:
          url: https://internal.${{github.event.inputs.environment}}.gritfinancial.org/api/gritAdmin/users/${{github.event.inputs.phoneNumber}}
          method: DELETE
          timeout: 10000
      - name: Response
        run: echo ${{ steps.deleteUser.outputs.response }}
```

I am not sure from where it is picking up node 20.
