### ISSUE TITLE
Receiving Error: {"message":"err is not defined"} After recent version

### ISSUE THREAD

**Issue by KenticoDevTrev** [fjogeleit/http-request-action#152]
All of a sudden i'm getting an error from the http request, the site URL loads file so maybe something to do with the recent version?

I can hit the URL and the site loads fine, so it's not a deployment issue, the repository was recently updated, possibly a bug with it?

![image](https://github.com/fjogeleit/http-request-action/assets/47198675/b15c8a4a-d59a-4abb-ba40-9ca30b791774)

```
    - name: Warmup Site
      if: ${{ inputs.warmup_url != '' }}
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ inputs.warmup_url }}
        method: 'GET'
        timeout: 20000 # warmup can take a while
        retryWait: 5000
        retry: 3 # will try for a max of 6 20-second requests, so 2 minutes threshold
```
