### ISSUE TITLE
Cloudflare proxies produce error: no response received

### ISSUE THREAD

**Issue by SMJSGaming** [fjogeleit/http-request-action#167]
I currently have an API which uses cloudflare for caching and SSL, and it seems that this causes issues with this action. Tools like insomnia can handle this same request without issues so I can confirm the issue is on the action side.

My action setup:
```yaml
- name: Deploy binary
  id: deploy-binary
  uses: fjogeleit/http-request-action@v1
  with:
    url: https://bin.smjsproductions.com/api/bin/deploy/smjs.gdintercept/v0.6.6-alpha.6
    method: POST
    username: ***
    password: ***
    contentType: multipart/form-data
    files: '{ "bin": "/home/runner/work/_actions/geode-sdk/build-geode-mod/main/combine/out" }'
```
