### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by Manouli** [fjogeleit/http-request-action#38]
Hello I am trying to use this action and I am getting an error about unescaped character. 

The action: 

```
- name: Clone pre-release branch configuration for iOS
        uses: fjogeleit/http-request-action@v1.8.2
        with:
          url: "https://api.appcenter.ms/v0.1/apps/xxx/xxx/branches​/${{ github.event.pull_request.head.ref }}/config"
          method: "POST"
          contentType: "application/json"
          data: '{"cloneFromBranch":"pre-release-appcenter"}'
          customHeader: '{"X-API-Token":"${{secrets.APP_CENTER_LOGIN_TOKEN}}"}'
```

The error output plus error: 

```
Run fjogeleit/http-request-action@v1.8.2
  with:
    url: https://api.appcenter.ms/v0.1/apps/xxx/xxx/branches​/xxx/config
    method: POST
    data: { "cloneFromBranch": "pre-release-appcenter" }
    customHeader: {"X-API-Token": "***"}
    files: {}
    timeout: 5000


Error: {"message":"Request path contains unescaped characters","data":"{ \"cloneFromBranch\": \"pre-release-appcenter\" }"}
```

Is there something obvious here that I am missing? Thank you in advance.
