### ISSUE TITLE
A way to see response in output?

### ISSUE THREAD

**Issue by domagojmedo** [fjogeleit/http-request-action#54]
![image](https://user-images.githubusercontent.com/12157224/186687825-a1c7a80d-6f30-4d12-9c0a-ac8752d4dc9a.png)
Is there a way to see response in the same step?

Right now you have to do add another step that will echo the response, can it be done in same step?
```
- name: Call webhook
  id: webhook
  uses: fjogeleit/http-request-action@v1
  with:
    url: 'my-url'
    method: 'POST'
- name: Webhook response
  run: |
    echo ${{ steps.webhook.outputs.response }}
    echo ${{ steps.webhook.outputs.headers  }}
```
