### ISSUE TITLE
Issue With Authentication?

### ISSUE THREAD

**Issue by aabouelleil-seniorlink** [fjogeleit/http-request-action#56]
Hello,

I have the following code in a github action:

```
    - name: Sync Airflow Dags
      id: syncAirflow
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{env.AIRFLOW_URL}}
        method: 'POST'
        username: ${{secrets.AIRFLOW_USERNAME_ALL}}
        password: ${{env.AIRFLOW_PASSWORD}}
        preventFailureOnNoResponse: 'true'
```

With the preventFailureOnResponse set to true, I get this warning:

```
{"message":"timeout of 5000ms exceeded","name":"Error","stack":"Error: timeout of 5000ms exceeded\n    at createError (/home/runner/work/_actions/fjogeleit/http-request-action/v1/dist/index.js:78:15)\n    at RedirectableRequest.handleRequestTimeout (/home/runner/work/_actions/fjogeleit/http-request-action/v1/dist/index.js:5415:16)\n    at RedirectableRequest.emit (node:events:390:28)\n    at Timeout.<anonymous> (/home/runner/work/_actions/fjogeleit/http-request-action/v1/dist/index.js:4071:12)\n    at listOnTimeout (node:internal/timers:557:17)\n    at processTimers (node:internal/timers:500:7)","config":{"method":"post","data":"{}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.21.4","Content-Length":2},"auth":{"username":"***","password":"***"},"baseURL":<REDACTED>","transformRequest":[null],"transformResponse":[null],"timeout":5000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":null,"maxBodyLength":null,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"ECONNABORTED"}
```

I do know that the API I am sending this request to requires the username to be base64 encoded, so I think this might be the reason for the timeout. I'm assuming this utility does not do that, is that correct? Is there an option for this?
