### ISSUE TITLE
Can't bypass Vercel's authentication

### ISSUE THREAD

**Issue by woochica** [fjogeleit/http-request-action#61]
I'm trying to send a request to an app that is hosted on Vercel. The instance is password protected.

This is my job configuration:

```
        uses: fjogeleit/http-request-action@v1.11.1
        with:
          url: 'https://myapp.vercel.app'
          method: 'POST'
          contentType: application/x-www-form-urlencoded
          data: '_vercel_password=<password>'
```

Output:

```
[yolo/e2e]   💬  ::debug::Instance Configuration: {"baseURL":"https://myapp.vercel.app","timeout":5000,"headers":{"Content-Type":"application/x-www-form-urlencoded"}}
[yolo/e2e]   💬  ::debug::Request Data: {"method":"POST","data":"_vercel_password=<password>","maxContentLength":null,"maxBodyLength":null}
[yolo/e2e]   ⚙  ::set-output:: requestError={"name":"Error","message":"Request failed with status code 401","status":401}
```

The following, I presume equivalent, CURL command works perfectly:

```
curl -s -D - -X POST -d "_vercel_password=<password>" https://myapp.vercel.app
```

This is how you can access [password protected deployments in Vercel](https://vercel.com/docs/concepts/projects/overview#bypassing-password-protection-programmatically).
