### ISSUE TITLE
Headers and Content-Type errors

### ISSUE THREAD

**Issue by cidrbl0ck** [fjogeleit/http-request-action#98]
First things first, this definitely isn't any sort of bug I'm sure. But more of a usage problem on my end. 
So here's my code:

```
name: AAP-Repo Project Update
on:
  push:
    branches:
      - main
jobs:
  http-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://ansible.domain.net/api/v2/projects/33/update/'
          method: 'POST'
          bearerToken: ${{ secrets.aap_bearer_token }}
          content: |
            '{"Content-Type": "application/json"}'
        id: http_request
      - name: Print HTTP Response
        run: echo "${{ steps.http_request.outputs.response }}"
```

This returns an error stating:
```
[http-request](https://github.com/company/sysops-aap/actions/runs/4441013002/jobs/7811192944#step:2:16)
Unexpected input(s) 'headers', 'Content-Type', valid inputs are ['url', 'method', 'contentType', 'data', 'files', 'file', 'username', 'password', 'timeout', 'bearerToken', 'customHeaders', 'preventFailureOnNoResponse', 'ignoreStatusCodes', 'escapeData', 'httpsCA', 'responseFile', 'retry', 'retryWait']
```

Ok, I'll change 'headers' to 'customHeaders'. So I change it to this:

```

name: AAP-Repo Project Update
on:
  push:
    branches:
      - main
jobs:
  http-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://ansible.domain.net/api/v2/projects/33/update/'
          method: 'POST'
          bearerToken: ${{ secrets.aap_bearer_token }}
          customHeaders: |
          contentType: '{"Content-Type": "application/json"}'
        id: http_request
      - name: Print HTTP Response
        run: echo "${{ steps.http_request.outputs.response }}"
```

Which then re-running the GH actin returns: no response from server.  Now test calls from Postman containing the same required info are successful. I'm wondering what the correct syntax for 'steps.http_request...' would be to echo out the API call before it's made?

**Comment by fjogeleit** [comment]
Hey,

the syntax for customHeaders should be a JSON String, so it should be:

```yaml
name: AAP-Repo Project Update
on:
  push:
    branches:
      - main
jobs:
  http-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://ansible.domain.net/api/v2/projects/33/update/'
          method: 'POST'
          bearerToken: ${{ secrets.aap_bearer_token }}
          customHeaders: '{"Content-Type": "application/json"}'
        id: http_request
      - name: Print HTTP Response
        run: echo "${{ steps.http_request.outputs.response }}"
```

You can get informations about headers and content are send when you enable the debug mode for your workflows. It is described in the readme how to enable it.
